from pathlib import Path

NAUTILUS_EDITORS_NOTE = """Behold the humble nautilus. Just about a foot in diameter, it is a slow bottom-dweller with short tentacles that moves through the water with an unsteady wobble. It's also 500 million years old and, in its day, was the best and brightest, using its newly evolved depth control to lay waste to acre after acre of scuttling crustacean prey.
We became interested in it here at Nautilus because, well, we stole its name. But also because (for a mollusk) it represents a remarkable intersection of science, math, myth, and culture. Since that is exactly the kind of intersection we love to write about, we decided to put together a little "teaser" issue all about it.
There's the science. The nautilus has a beautiful, logarithmic, and fractal spiral in its shell. Benoit Mandelbrot, discoverer of the fractal, gives us a few words on that topic. One of the world's foremost nautilus experts, Peter Ward, tells us about nautilus evolution and biology, and about his life of nautilus research.
Then, the myth: from Jules Verne's fictional submarine, to Oliver Wendell Holmes' poem, to how and why we turn science into story.
Two chapters, one undersea creature. Welcome aboard.
Michael Segal
    Editor in Chief"""

COQUI_SINGLE_SPEAKER_MODELS = [
    "tts_models/en/ek1/tacotron2",
    "tts_models/en/ljspeech/tacotron2-DDC",
    "tts_models/en/ljspeech/tacotron2-DDC_ph",
    "tts_models/en/ljspeech/glow-tts",
]

COQUI_VKTS_SPEAKER_INDICES = [
    "p225",
    "p226",
    "p227",
    "p228",
    "p229",
    "p230",
    "p231",
    "p232",
    "p233",
    "p234",
    "p236",
    "p237",
    "p238",
    "p239",
    "p240",
    "p241",
    "p243",
    "p244",
    "p245",
    "p246",
    "p247",
    "p248",
    "p249",
    "p250",
    "p251",
    "p252",
    "p253",
    "p254",
    "p255",
    "p256",
    "p257",
    "p258",
    "p259",
    "p260",
    "p261",
    "p262",
    "p263",
    "p264",
    "p265",
    "p266",
    "p267",
    "p268",
    "p269",
    "p270",
    "p271",
    "p272",
    "p273",
    "p274",
    "p275",
    "p276",
    "p277",
    "p278",
    "p279",
    "p280",
    "p281",
    "p282",
    "p283",
    "p284",
    "p285",
    "p286",
    "p287",
    "p288",
    "p292",
    "p293",
    "p294",
    "p295",
    "p297",
    "p298",
    "p299",
    "p300",
    "p301",
    "p302",
    "p303",
    "p304",
    "p305",
    "p306",
    "p307",
    "p308",
    "p310",
    "p311",
    "p312",
    "p313",
    "p314",
    "p316",
    "p317",
    "p318",
    "p323",
    "p326",
    "p329",
    "p330",
    "p333",
    "p334",
    "p335",
    "p336",
    "p339",
    "p340",
    "p341",
    "p343",
    "p345",
    "p347",
    "p351",
    "p360",
    "p361",
    "p362",
    "p363",
    "p364",
    "p374",
    "p376",
]

AWS_MODEL_NAMES = ["Nicole", "Russell"]

GCP_MODEL_NAMES = [
    "en-AU-Neural2-A",
    "en-AU-Neural2-B",
    "en-AU-Neural2-C",
    "en-AU-Neural2-D",
    "en-AU-News-E",
    "en-AU-News-F",
    "en-AU-News-G",
    "en-AU-Standard-A",
    "en-AU-Standard-B",
    "en-AU-Standard-C",
    "en-AU-Standard-D",
    "en-AU-Wavenet-A",
    "en-AU-Wavenet-B",
    "en-AU-Wavenet-C",
    "en-AU-Wavenet-D",
]

DATA_DIR = Path(__file__).parents[1] / "data"
NAUTILUS_EPUB_DIR = DATA_DIR / "nautilus_epub"
DEV_OUTPUT_DIR = DATA_DIR / "tts_output/dev"
OUTPUT_DIR = DATA_DIR / "tts_output"
